// 构建期生成繁体内容（opencc 简→繁/香港用词）。由 npm run build 在 vite-ssg 之前自动执行。
// 输出：src/data/seoTopics.tw.js（专题页繁体）、src/i18n.tw.js（应用页 UI 繁体词典）。勿手改。
import { seoTopics } from "../src/data/seoTopics.js";
import { uiEn } from "../src/i18n.en.js";
import * as OpenCC from "opencc-js";
import { writeFileSync, readFileSync, readdirSync, statSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const convert = OpenCC.Converter({ from: "cn", to: "hk" });
const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, "../src");

function deep(v) {
  if (typeof v === "string") return convert(v);
  if (Array.isArray(v)) return v.map(deep);
  if (v && typeof v === "object") {
    const o = {};
    for (const k in v) o[k] = deep(v[k]);
    return o;
  }
  return v;
}

// 1) 专题页繁体
const tw = {};
for (const key in seoTopics) tw[key] = deep(seoTopics[key]);
writeFileSync(
  join(SRC, "data/seoTopics.tw.js"),
  "// AUTO-GENERATED by scripts/gen-i18n.mjs (opencc cn->hk). 请勿手改。\n" +
    "export const seoTopicsTw = " + JSON.stringify(tw, null, 2) + ";\n\n" +
    "export const seoTopicListTw = Object.values(seoTopicsTw);\n",
);

// 2) 应用页 UI 繁体词典：扫描所有 .vue 里的 t("...") / t('...') 简体串
const hasCjk = /[一-鿿]/;
const tCall = /\bt\(\s*(['"])((?:(?!\1)[\s\S])+?)\1\s*\)/g;
const found = new Set();
function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p);
    else if (name.endsWith(".vue") || name.endsWith(".js")) {
      const src = readFileSync(p, "utf8");
      let m;
      while ((m = tCall.exec(src))) {
        const s = m[2];
        if (hasCjk.test(s)) found.add(s);
      }
    }
  }
}
walk(SRC);
// 英文词典的 key（简体串）是"要翻译的串"主清单——也一并生成繁体
for (const k of Object.keys(uiEn)) if (hasCjk.test(k)) found.add(k);
const uiTw = {};
for (const s of found) uiTw[s] = convert(s);
writeFileSync(
  join(SRC, "i18n.tw.js"),
  "// AUTO-GENERATED by scripts/gen-i18n.mjs (opencc cn->hk). 请勿手改。\n" +
    "export const uiTw = " + JSON.stringify(uiTw, null, 2) + ";\n",
);

console.log("[gen-i18n] seoTopics.tw.js:", Object.keys(tw).length, "topics | i18n.tw.js:", found.size, "ui strings");
