// 构建期生成繁体 SEO 内容（opencc 简→繁/香港用词）。
// 由 npm run build 在 vite-ssg 之前自动执行；输出 src/data/seoTopics.tw.js（勿手改）。
import { seoTopics } from "../src/data/seoTopics.js";
import * as OpenCC from "opencc-js";
import { writeFileSync } from "fs";

const convert = OpenCC.Converter({ from: "cn", to: "hk" });

// 深度转换所有字符串值；ASCII（路径、eyebrow 等）原样保留（opencc 只动中文）。
function deep(v) {
  if (typeof v === "string") return convert(v);
  if (Array.isArray(v)) return v.map(deep);
  if (v && typeof v === "object") {
    const o = {};
    for (const k in v) o[k] = deep(v[k]);
    return o;
  }
  return v;
}

const tw = {};
for (const key in seoTopics) tw[key] = deep(seoTopics[key]);

const out =
  "// AUTO-GENERATED by scripts/gen-i18n.mjs (opencc cn->hk). 请勿手改。\n" +
  "export const seoTopicsTw = " +
  JSON.stringify(tw, null, 2) +
  ";\n\nexport const seoTopicListTw = Object.values(seoTopicsTw);\n";

writeFileSync(new URL("../src/data/seoTopics.tw.js", import.meta.url), out);
console.log("[gen-i18n] seoTopics.tw.js written, topics:", Object.keys(tw).length);
